platform :ios, '9.0'

target 'MET-SDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MET-SDK
  pod 'SwiftLint'

  target 'MET-SDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
