platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'MerlinMetPod' do

  use_frameworks!
  pod 'SwiftLint'
  pod 'Moya'

  target 'MerlinMetPodTests' do
    inherit! :search_paths
    pod 'Moya'
  end

end
