# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'METDemoImplementation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'MerlinMet', :git => 'https://github.com/merlinapp/met_sdk_ios.git'

end
