platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/merlinapp/met_sdk_specs.git'

target 'METDemoImplementation' do
  use_frameworks!
  pod 'MerlinMetPod'
end
